# Generated by Django 5.0.6 on 2024-07-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
