# Generated by Django 5.0.6 on 2024-07-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_alter_description_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
    ]
